import json, pathlib, hashlib
root=pathlib.Path('.')
d=json.load(open('work/corpus/dataset-v01.json'))
# Original paraphrases, each bounded to the source basis recorded below.
rows=[
(2,'Representativeness and the research question','generalizability,representativeness,external validity','This viewpoint distinguishes describing a population from learning about a causal mechanism. Representative sampling can serve descriptive aims, but does not itself establish a valid causal comparison. The authors emphasize controlled comparisons and understanding when effects vary. Read this as an argument about research aims, rather than a rule to disregard the population to which results will be applied.','Does a representative sample guarantee a valid causal study?','No. Representativeness alone does not establish a valid causal comparison. This paper distinguishes population description from scientific generalization and emphasizes the conditions under which findings apply.',[19,30,41]),
(3,'Making the causal question explicit','causal inference,causal language,research question','This commentary argues that researchers should clearly state when their objective is causal. Calling an intended causal estimate merely an association can obscure the question and its interpretation. Explicit objectives help align the analysis with the question; wording alone does not supply the evidence needed for a causal conclusion.','Why explicitly state a causal objective?','The commentary argues that an explicit causal objective reduces ambiguity in the question, analysis, and interpretation. Describing an objective as causal does not by itself validate the resulting estimate.',[11,39]),
(4,'Designing useful comparisons in real-world data','new user,active comparator,immortal time,study design','This overview emphasizes design before statistical adjustment. It discusses starting follow-up at treatment initiation, comparing treatment alternatives, and accounting for induction and latency. Consistent definitions of treatment initiation and follow-up help prevent immortal-time bias. Propensity scores address measured covariate differences; their use does not remove the need for a sound design.','Can propensity-score adjustment replace careful study design?','No. The overview emphasizes new-user designs, active comparators, and consistent timelines as design choices. Propensity scores can balance measured covariates but do not replace those choices.',[30,14]),
(5,'Thinking through causation','Hill,causation,causal viewpoints','In the scanned pages inspected, Hill asks how evidence of association contributes to a causal judgment. He presents viewpoints to consider, rather than an automatic checklist that proves causation. The discussion emphasizes weighing the evidence and alternative explanations. These pages support an introduction to causal reasoning, not a complete account of every viewpoint in the paper.','Are Hill’s viewpoints a checklist that proves causation?','No. Hill says the viewpoints do not provide hard-and-fast rules or indisputable proof. They help organize judgment about the evidence and alternative explanations.',[11,19]),
(6,'Why a significant finding can still mislead','false positive,power,bias,selective reporting','This essay develops a framework in which the credibility of research findings depends on power, bias, and the balance of true and false relationships being investigated. It discusses how flexible analyses and selective pursuit of significance can undermine findings. The framework should not be read as a measured false-finding percentage for every field or individual study.','Does statistical significance establish that a research claim is true?','No. In this framework, credibility also depends on power, bias, and the underlying mix of relationships being tested. Significance alone is insufficient to establish a claim.',[13,19,41]),
(7,'Interpreting hazard ratios carefully','hazard ratio,survival,selection bias','Hernán describes two difficulties with causal interpretation of hazard ratios: an average can depend on the duration of follow-up, and comparisons later in follow-up condition on remaining event-free. Treatment groups can therefore contain different sets of survivors over time. This record introduces those conceptual cautions; it does not provide a numerical reanalysis.','Why can a single average hazard ratio be hard to interpret?','When hazards vary over time, the average hazard ratio can depend on follow-up duration. In addition, later hazard comparisons condition on surviving without the event, which can change the composition of the groups being compared.',[41,14]),
(8,'Time-related biases in database studies','immortal time,latency,protopathic bias,time window','Using a COPD database example, this paper illustrates several time-related biases, including protopathic, latency, immortal-time, and time-window biases. Estimates changed substantially when timing problems were addressed. The teaching point is to examine how cohort entry, exposure, and outcome time are aligned; the example is not evidence that every bias has the same direction in every study.','Why examine study timelines before interpreting a drug association?','Misaligned exposure and follow-up times can produce misleading associations. This paper’s examples show why timing choices need explicit examination before an apparent treatment effect is interpreted.',[30,14]),
(9,'When adjustment can introduce bias','overadjustment,mediator,causal diagram','This paper distinguishes overadjustment bias from unnecessary adjustment. Controlling for an intermediate variable, or a descendant of one, can bias estimation of the total exposure effect. Other unnecessary adjustments may change precision without changing bias. Choosing covariates therefore requires thinking about causal roles and the effect being estimated, rather than simply including more variables.','Is adjusting for more variables always better?','No. Adjusting for an intermediate variable can bias a total-effect estimate. The paper distinguishes this overadjustment bias from unnecessary adjustment that affects precision without affecting bias.',[14,11]),
(10,'Recognizing systematic error','bias,selection,measurement,confounding','This introduction describes bias as systematic error and organizes routes by which it enters intervention studies: treatment exposure, inclusion in a study, and assessment or measurement. It emphasizes preventing bias during design, addressing it in analysis when feasible, and examining remaining bias when interpreting results.','At what stage should we address bias?','Start during study design. If a bias cannot feasibly be avoided, consider appropriate analytic approaches and assess and discuss the remaining bias when interpreting the findings.',[14,19]),
(11,'Depletion of susceptible users','depletion of susceptibles,duration of use,new user','This hormone-therapy study illustrates how adverse-event associations can vary with duration of use. Users who remain on treatment later may differ from those at initiation because susceptible individuals experience events earlier. The authors recommend considering duration of use alongside current use. This record uses the study to teach design and interpretation, not to advise treatment choices.','Why distinguish early from longer-term users?','The population still using treatment later may have fewer susceptible individuals. In this example, risks varied by duration, so a current-use comparison alone could conceal relevant changes over time.',[14,20,41]),
(12,'Misclassification is not always toward the null','misclassification,measurement,claims,quantitative bias','This review describes measurement problems in claims data, such as filled prescriptions that are not taken and conditions absent from billing records. It discusses misclassification in active-comparator studies and demonstrates that nondifferential misclassification can bias effects away from the null. Quantifying measurement uncertainty can add information beyond an analysis of random error alone.','Does nondifferential misclassification always bias toward the null?','No. This review demonstrates bias away from the null in an active-comparator setting. The consequences depend on the measurement problem and comparison, so the direction should not be assumed.',[35,38,8]),
(13,'Selection bias through causal structure','collider,selection bias,informative censoring','This paper connects examples of selection bias through a common causal structure: conditioning on a common effect of variables connected to exposure and outcome. It contrasts that structure with confounding through common causes. The framework helps learners reason about selection and censoring instead of treating every named bias as unrelated.','How does this paper distinguish selection bias from confounding?','It associates selection bias with conditioning on common effects, and confounding with common causes of exposure and outcome. This structural view links otherwise different examples of selection bias.',[11,14]),
(15,'Drawing study timelines','study diagram,timeline,reproducibility','This paper proposes standardized graphical representations of database-study implementation. Explicit diagrams can communicate design choices that prose leaves ambiguous and make key variables easier to reproduce. A diagram supports review and communication; it does not establish that the chosen design yields an unbiased estimate.','What does a study-design diagram add?','A standardized diagram makes design timing and implementation choices easier to inspect, communicate, and reproduce. It complements the methods description rather than establishing validity on its own.',[30,39]),
(16,'Making study implementation explicit','STaRT-RWE,protocol,transparency,reproducibility','STaRT-RWE uses structured tables and diagrams to communicate how real-world-evidence studies are implemented. It complements reporting checklists rather than being a checklist itself. Clear specifications help others understand and assess the study, but do not guarantee unbiased findings or fully establish whether a data source is fit for purpose.','Does completing STaRT-RWE establish study validity?','No. It makes implementation decisions clearer and supports review, but the authors explicitly distinguish transparent reporting from valid methodology. Separate consideration of data fitness is also needed.',[39,30,35]),
(17,'Using people as their own comparators','self controlled,case crossover,SCCS','This review compares self-controlled observational designs, including case-crossover and self-controlled case series. Comparing periods within the same person protects against confounders that remain stable over time. The designs still have limitations involving exposure trends, duration, and transient effects; no one design is generally superior.','Do self-controlled designs remove all confounding?','No. Their shared advantage concerns confounders that are stable over time. Time-related changes and exposure trends can still matter, and suitability depends on the question and design.',[30,14]),
(19,'Handling missing data with explicit assumptions','missing data,imputation,inverse probability weighting','This paper compares principled missing-data approaches, including multiple imputation and inverse probability weighting, using a challenge with known missingness mechanisms. Naive analyses can be misleading; suitable methods sometimes mitigate the problem. The lesson is to consider the missingness process and analytic assumptions, rather than assume a preferred method automatically repairs missing data.','Does multiple imputation automatically solve missing-data bias?','No. The paper ties appropriate analysis to missing-data mechanisms and compares several approaches. Principled methods can mitigate bias in suitable circumstances; they do not provide an automatic fix.',[6,14]),
(20,'Starting with a target trial','target trial,emulation,causal inference','This framework makes explicit the randomized trial that would answer a comparative-effectiveness or safety question, then evaluates how an observational analysis emulates it. Specifying the target helps organize design choices, analysis, and criticism. Emulation remains an observational exercise and should not be mistaken for actually randomizing participants.','What is the purpose of specifying a target trial?','It makes the causal question and intended experiment explicit, so the observational design can be assessed against that target and common methodological pitfalls can be identified.',[11,30]),
(21,'Learning from negative controls','negative control,bias,confounding','This paper proposes exposure and outcome negative controls to help detect spurious associations. Appropriate controls can reveal suspected or unsuspected sources of confounding and other error. Their usefulness depends on the conditions under which they detect the relevant bias; a control is not a universal certificate of validity.','What can a negative control contribute?','A suitably chosen exposure or outcome control can help detect spurious associations or other errors. Its usefulness depends on the conditions connecting the control to the bias being investigated.',[14,19,10]),
(22,'Restriction as a design choice','restriction,confounding,comparability','This statin-study example examines successive restrictions that make treatment groups more comparable. Estimates moved closer to randomized-trial findings as restrictions were applied. It illustrates how design can change confounding, but does not establish that every restriction, particularly one involving adherence, is appropriate for every research question.','Should every study copy the restrictions in this example?','No. The findings concern a particular study and set of restrictions. Use the example to consider comparability and the population being studied, rather than treat its restrictions as a universal recipe.',[30,14]),
(23,'Different methods can target different effects','propensity score,IPTW,estimand,effect modification','This worked example shows that propensity-score matching and a common form of treatment weighting can summarize different causal contrasts. With effect-measure modification, weights based on treated people and weights based on the whole study population can yield different estimates. A discrepancy does not necessarily mean one method failed to control confounding.','Must matching and IPTW produce the same effect estimate?','No. They can weight subgroup effects differently and target different populations. When effects vary across those groups, different summary estimates can be expected even without residual confounding in the example.',[41,14,11]),
(24,'Tracking treatment as it changes','time varying exposure,treatment episode,latency,switching','This conceptual overview organizes time-varying exposure problems around treatment episodes, time-varying confounders, cumulative exposure and latency, and treatment switching. Different modeling choices can produce substantially different estimates. It highlights the importance of defining and quantifying exposure carefully; this abstract-based record does not give implementation instructions for advanced models.','What exposure decisions matter when treatment changes over time?','The overview highlights construction of treatment episodes, handling time-varying confounders, cumulative exposure and latency, and treatment switching. These choices affect what an analysis represents and can materially change estimates.',[20,30,1]),
(25,'A shared language for adherence','adherence,initiation,implementation,discontinuation','This taxonomy addresses inconsistent terminology for medication-taking behavior. It separates adherence into initiation, implementation, and discontinuation, and distinguishes the behavior from managing adherence and studying it. For a learner, the practical question is which part of medication-taking a measure is intended to capture.','Which phases does this adherence taxonomy distinguish?','It separates adherence into initiation, implementation, and discontinuation. Naming the phase helps make the behavior under study explicit instead of relying on an ambiguous general adherence label.',[20,38]),
(26,'Propensity scores and heterogeneous effects','propensity score,heterogeneity,matching,weighting','This paper discusses propensity scores for measured confounding when treatment effects differ across patient characteristics. Matching and weighting can estimate effects in differently defined populations. It also considers sensitivity analyses for unmeasured confounding among people treated contrary to prediction. Choosing an approach requires attention to the target population and remaining uncertainty.','Why identify the target population when using propensity scores?','Different matching or weighting implementations can estimate effects for different populations. When treatment effects are heterogeneous, that choice affects the overall effect being summarized.',[14,41,10]),
(27,'Choosing propensity-score weights','propensity score weighting,ATE,ATT,overlap,estimand','This primer compares weighting approaches that target effects in the whole population, treated people, or groups with greater treatment equipoise. It starts with the scientific question and the population of interest. The authors offer implementation guidance rather than a competition identifying one best method. Adjustment concerns measured characteristics and still relies on causal assumptions.','Do all propensity-score weights estimate the same effect?','No. Weighting methods can target different populations and causal effects. Choose the scientific target first, then consider an appropriate weighting method and its assumptions.',[11,14,41]),
(28,'Assessing residual confounding','sensitivity analysis,unmeasured confounding,external adjustment','This paper organizes sensitivity analyses for residual confounding in healthcare databases. Approaches include varying informed assumptions, asking how strong confounding would need to be to explain an association, and incorporating external information. These analyses make uncertainty more explicit; their conclusions remain dependent on the assumptions and information used.','What does a sensitivity analysis add to a discussion of confounding?','It can quantify how conclusions change under assumptions about unmeasured confounding, rather than merely mention that confounding may remain. The paper also describes approaches using external information.',[10,8,14]),
(29,'Comparing disease-risk and propensity scores','disease risk score,propensity score,simulation','This simulation study compares disease-risk scores, propensity scores, and direct covariate adjustment. Performance varies with exposure–covariate correlation, model specification, and events per covariate. Its results support examining the data and setting; they do not establish one method as best for every cohort study.','Does this simulation establish one universally best score method?','No. Performance depended on the simulated conditions, including covariate correlation, model specification, and events per covariate. The findings support conditional comparisons rather than a universal ranking.',[1,14,19]),
(30,'When confounder effects change over time','time modified confounding,time varying confounding,MSM','This paper distinguishes a confounder whose value changes over time from one whose effect on treatment or outcome changes over time. It calls the latter time-modified confounding. Its example and simulation examine treatment weights that account for this change, emphasizing correct model specification rather than assuming a time-fixed association.','How is time-modified confounding different from time-varying confounding?','In the paper’s distinction, time-varying confounding concerns changing confounder values; time-modified confounding concerns changing effects of a confounder on treatment or outcome. Both affect how the analysis should represent time.',[1,14])
]
lookup={a['number']:a for a in d['articles']}
full={2:('Full-text discussion','Main discussion: statistical versus scientific inference'),5:('Selected scanned pages','Printed pages 295 and 299'),7:('Full-text sections','Introduction; Problem 1 and Problem 2'),16:('Full-text sections','Discussion and limitations'),27:('Selected full-text pages','Printed pages 1–2: introduction and choosing an estimand')}
for n,title,topics,summary,q,answer,cids in rows:
 a=lookup[n]; aid=a['article_id']; src=json.load(open(f'work/corpus/{aid}.json'))
 basis,locator=full.get(n,('Abstract','Abstract'))
 url=src.get('source_url') if n in full else src['abstract_url']
 if n==5:url='https://pmc.ncbi.nlm.nih.gov/articles/PMC1898525/'
 if n==27:url='https://www.rama.mahidol.ac.th/ceb/sites/default/files/public/pdf/journal_club/2020/bmj.l5657.full.pdf'
 eid=aid+'-OVERVIEW'; qid='Q'+aid[1:]+'A'
 limitations=['This is a provisional teaching paraphrase and mapping, not an expert-validated record.']
 if basis=='Abstract':limitations.append('Based on the abstract only. Detailed implementation, assumptions, and numerical examples require full-text review.')
 if a.get('correction_notices'):limitations.append('An indexed correction remains to be assessed. This draft is limited to broad concepts; corrected details are not validated.')
 mappings=[{'competency_id':f'C{c:02}','coverage':'limited_aspect','rationale':f'The teaching focus on {topics.split(",")[0]} relates to this competency; it does not establish complete coverage.','evidence_ids':[eid],'status':'provisional'} for c in cids]
 record={'record_id':'T'+aid[1:],'article_id':aid,'record_type':'Provisional teaching overview','title':title,'learner':d['learner'],'topics':topics.split(','),'search_phrases':[q],'prerequisites':['Basic epidemiology'],'teaching_summary':summary,'summary_evidence_ids':[eid],'learning_objectives':[f'Explain the central idea: {title.lower()}.'],'key_lessons':[{'text':answer,'evidence_ids':[eid]}],'limitations':[{'text':s,'evidence_ids':[]} for s in limitations],'competency_mappings':mappings,'questions':[{'question_id':qid,'question':q,'reference_answer':answer,'evidence_ids':[eid],'required_points':[],'status':'draft','approved_answer':None}],'cannot_answer':['Study-specific causal conclusions or implementation details beyond the inspected source.'],'version':'0.2','review':{'status':'provisional','reviewer':None,'reviewed_at':None},'student_release_approved':False,'article_url':a['doi_url'],'evidence_basis':basis,'authorship_note':'AI-drafted original teaching paraphrase. No ISPE endorsement claimed.'}
 d['teaching_records'].append(record)
 d['evidence_index'].append({'evidence_id':eid,'article_id':aid,'locator':locator,'support_paraphrase':summary,'url':url or a['doi_url'],'source_snapshot_sha256':src.get('sha256'),'locator_note':'Source basis limits the scope of this provisional record.'})
 a['full_text_review_status']=basis+' inspected for this draft; no expert validation'
 a['availability_status']='source_basis_recorded'
 a['retrieval_attempts']=src['attempts']
d['teaching_records'].sort(key=lambda r:r['article_id'])
# Old sample record IDs were sequential, so normalize all record IDs to article IDs.
for r in d['teaching_records']:r['record_id']='T'+r['article_id'][1:]
d['version']='0.2';d['status']='Internal MVP preview — provisional content'
d['retrieval_contract'].update({'preview_mode':'All 30 provisional records are available in an explicitly labelled local MVP preview. Expert approval is not required to test this workflow.','eligible_for_student_retrieval':'This MVP displays draft content for testing; no records have expert approval. Public production release remains a separate decision.','known_question':'For an explicitly selected question, return reference_answer verbatim with draft status and source evidence.','free_text':'Retrieve candidate readings and stored questions; require explicit question selection before displaying a stored answer. No model-generated response in this version.'})
for i in d['review_issues']:
 if i['id']=='R01':i.update(priority='future_validation',issue='All 30 teaching records and 33 stored answers are provisional.',action='Pilot the workflow now; record expert feedback when available without representing drafts as approved.')
 if i['id']=='R02':i.update(priority='content_followup',action='Broad conceptual drafts are included and flagged. Assess indexed corrections before extending to affected numerical or technical details.')
 if i['id']=='R06':i.update(priority='content_followup',issue='Full-text depth varies across records; mappings are provisional.',action='Use the pilot to identify which records need deeper extraction. Unmapped competencies are not proof of an exhaustive coverage gap.')
json.dump(d,open('outputs/pilot-dataset.json','w'),ensure_ascii=False,indent=2)
json.dump(d,open('outputs/prototype/public/dataset.json','w'),ensure_ascii=False,indent=2)
md=['# Teaching records — MVP v0.2','Audience: trainee with basic epidemiology knowledge. All 30 selected readings are included. All summaries and mappings are provisional.','']
for r in d['teaching_records']:
 a=next(a for a in d['articles'] if a['article_id']==r['article_id'])
 md += [f"## {r['article_id']} · {r['title']}",f"[Publication]({a['doi_url']}) · Evidence basis: {r['evidence_basis']}",'',r['teaching_summary'],'', 'Competencies: '+', '.join(m['competency_id'] for m in r['competency_mappings']),'']
 for q in r['questions']:md += ['**'+q['question']+'**',q['reference_answer'],'']
pathlib.Path('outputs/teaching-records.md').write_text('\n'.join(md))
print('Records',len(d['teaching_records']),'Questions',sum(len(r['questions']) for r in d['teaching_records']))
